### ISSUE TITLE
How to change the size of the scrollbar?

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#54]
To change the size of the scrollbar of the editor, one can add for example this code in the document geany.css that is located in .geany:
```
/* size of the scrollbar */
scrollbar slider {
    min-width: 10px;
    border-right: 10px solid transparent;
}
```
The CSS affects the scrollbar of the editor and also the tabs `Documents` and `Files` (plugin `File Browser`) of the sidebar, but not the tab `Preview` of the sidebar, even if I deactivate the plugin Xi/Tweaks.

Yesterday I opened a discussion at geany / discussions with the title `Is there a possibility to change the size of the scrollbar of the sidebar?`. The number of the discussion is 3953. According to the maintainer "the sidebar is standard GTK only". But it seems to be that the plugin `Preview` is using something else.

When using an eink-display the horizontal and the vertical scrollbar of the tab `Preview` are thin. The vertical scrollbar is so thin, that I have not only big difficulties to grab the scrollbar, but also to see the scrollbar.

Is there a way to change the size of the scrollbar for the tab `Preview`?

**Comment by xiota** [comment]
Preview scrollbar is rendered by webkit2gtk.  You can change it by editing the `.css` files in the plugin directory.  Changes to `preview.css` require restarting Geany to take effect.
```css
* {
	scrollbar-width: none;
}
```

Useful reference: [mdn/scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width)

FYI, I haven't read your other recent posts/comments, but will go through them when I look at the shortcuts issue.

**Comment by ralf3u** [comment]
The code of the last comment does not work. I'm sure that it has to do something with the star symbol. I think that the star symbol has to be replaced by something else. But I don't know what to use instead.
I tried to put `scrollbar-width: none` in the HTML-code in a div-tag or body-tag. But also that does not work.
Even if it would work, there will be only three possibilities: auto, thin and none. 
This could be interesting because one can define the scrollbar in px:
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
But I don't know if it works and how to use it.

**Comment by xiota** [comment]
On my computer, `none` worked, but `auto` and `thin` look the same.  The following works on my computer:

```css
::-webkit-scrollbar {
	width: 13px;
}

::-webkit-scrollbar-track {
	background-color: #eff0f1;
	width: 13px;
	border-left: 1px;
	border-right: 0;
	border-top: 0;
	border-bottom: 0;
	border-style: solid;
	border-color: #bcbebf;
}

::-webkit-scrollbar-thumb {
	background-color: #969899;
	border-radius: 15px;
	border: 3px solid transparent;
	background-clip: padding-box;
}
```

While editing, work with `markdown.css`, since it's reloaded live.  Then move to `preview.css` when done.
